name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Rename binary
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            mv target/release/apple_music_rpc.exe apple_music_rpc_windows.exe
          else
            mv target/release/apple_music_rpc apple_music_rpc_macos
          fi

      - name: Upload binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            apple_music_rpc_windows.exe
            apple_music_rpc_macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}